version: "3"

services:
  api:
    build: .
    container_name: 'api-container'
    command: bash entrypoint.sh
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    container_name: 'postgres-container'
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

volumes:
  pg_data: